<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>
    
    <p>
        <label for="nama">Nama</label>
        <?php echo $form->render('nama'); ?>
    </p>

    <p>
        <label for="nrp">NRP</label>
        <?php echo $form->render('nrp'); ?>
    </p>

    <p>
        <label for="no_telp">Nomor Telepon</label>
        <?php echo $form->render('no_telp'); ?>
    </p>

    <p>
        <label for="alamat">Alamat</label>
        <?php echo $form->render('alamat'); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $form->render('password'); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>
    <?php echo $this->tag->linkTo("/", " Kembali"); ?>


</form>