<?php

if ($this->session->isAdmin) {
    // Retrieve its value
    $nama = $this->session->nama_user;
    $lab = $this->session->isAdmin;

    echo "Welcome, Admin " . $nama . "!</br>";
    echo $this->tag->linkTo(["/pengguna/logout", "Logout", 'class' => 'btn btn-warning']);

    ?>
    <div>
        <h5>Menu</h5>
        <ul>
            <li><?php echo $this->tag->linkTo("/admin/listPC", "Melihat daftar PC"); ?>
            <li><?php echo $this->tag->linkTo("/admin/listReservasiPC/", "Mengatur reservasi PC"); ?>
        </ul>
        <ul>
            <li><?php echo $this->tag->linkTo("/admin/jadwalPemakaianRuangan/".$this->session->isAdmin, "Melihat jadwal pemakaian lab"); ?>
            <li><?php echo $this->tag->linkTo("/admin/listPermohonanRuangan/".$this->session->isAdmin, "Mengonfirmasi peminjaman lab"); ?>
        </ul>
    </div>

<?php    
}
else {
    echo "Who are you?";
    header("refresh:2;url=/pengguna/loginpage");
}