<?php

if ($this->session->isAdmin) { ?>
    <h2>Form tambah PC</h2>

    <?php echo $this->tag->form("/admin/tambahpc"); ?>
        
        <p>
            <label for="nama">Nama</label>
            <?php echo $form->render('nama', ['required'=>True]); ?>
        </p>

        <p>
            <label for="ip">IP</label>
            <?php echo $form->render('ip', ['required'=>True]); ?>
        </p>

        <p>
            <label for="hdd">Ukuran Hardisk</label>
            <?php echo $form->render('hdd', ['required'=>True]); ?>
        </p>

        <p>
            <label for="ram">RAM</label>
            <?php echo $form->render('ram', ['required'=>True]); ?>
        </p>

        <p>
            <label for="processor">Processor</label>
            <?php echo $form->render('processor', ['required'=>True]); ?>
        </p>

        <p>
            <label for="gpu">GPU</label>
            <?php echo $form->render('gpu', ['required'=>True]); ?>
        </p>

        <p>
            <label for="status">Status</label>
            <?php echo $form->render('status', ['required'=>True]); ?>
        </p>
        
        <p>
            <?php echo $this->tag->submitButton("Tambah!"); echo $this->tag->linkTo("/admin/listPC", " Kembali");?>
        </p>

</form>

<?php    
}
else {
    echo "Who are you?";
    header("refresh:2;url=/pengguna/loginpage");
}