<?php

if ($this->session->has('auth')) {
    // Retrieve its value
    $id = $this->session->get('auth', 'nama');

echo "Welcome " . $id . "!</br>";
echo $this->tag->linkTo("/pengguna/logout", "Logout");
}
else {
    ?>
    <div class="page-header">
        <h1>Welcome to Lammas</h1>
    </div>
    <p>Already have an account? Login below!</p>
    <?php
    echo $this->tag->linkTo(
        "/pengguna/loginpage",
        "Login!"
    );?>
    
    <p>Don't have one? <?php echo $this->tag->linkTo("signup", "Sign Up Here!");?></p>
    <?php
}
