<?php

if ($this->session->has('nama_user')) {
    // Retrieve its value
    $nama = $this->session->nama_user;

    echo "Welcome " . $nama . "!</br>";
    echo $this->tag->linkTo("/pengguna/logout", "Logout");
}
else {
    ?>
    <div class="page-header">
        <h1>Welcome to Lammas</h1>
    </div>
    <p>
        Already have an account?</br>Login below!</br>
        <?php
        echo $this->tag->linkTo(
            "/pengguna/loginpage",
            "Login"
        );?>
    </p>
    <p>Don't have one? <?php echo $this->tag->linkTo("signup", "Sign Up Here!");?></p>
    <?php
}
