<?php

if ($this->session->isAdmin) {

    echo "<h5>List PC Lab<h5>";
    echo $this->tag->linkTo("/admin/dashboard", "Kembali ke dashboard");
    echo "</br>";
    echo $this->tag->linkTo("/admin/tambahpcpage", "Tambah PC");

    foreach ($pcs as $pc) { ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Nama PC</th>
            <th>IP</th>
            <th>Ukuran Hardisk</th>
            <th>RAM</th>
            <th>Processor</th>
            <th>GPU</th>
            <th>Status</th>
            <th>Pengaturan</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">PC quantity: <?php echo $pcs->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php 
        $i=1;
        foreach ($pcs as $pc) { ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $pc->nama_pc; ?></td>
                <td><?php echo $pc->ip; ?></td>
                <td><?php echo $pc->hdd; ?></td>
                <td><?php echo $pc->ram; ?></td>
                <td><?php echo $pc->processor; ?></td>
                <td><?php echo $pc->gpu; ?></td>
                <td><?php echo $pc->status_pc; ?></td>
                <td><?php echo $pc->status_pc; echo " ".$this->tag->linkTo("/admin/hapusPC/".$pc->id_pc, "Hapus"); ?></td>
            </tr>
        <?php $i++; } ?>
        </tbody>
    </table>
    
<?php    
    }
}
else {
    echo "You must login to see this page";
    header("refresh:2;url=/pengguna/loginpage");
}