<?php
if ($this->session->isAdmin) {

echo "<h5>List Reservasi PC Lab<h5>";
echo $this->tag->linkTo("/admin/dashboard", "Kembali ke dashboard");

foreach ($ppcs as $ppc) { ?>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
    <tr>
        <th>#</th>
        <th>Jenis Peminjaman</th>
        <th>Keperluan</th>
        <th>Status</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php 
    $i=1;
    foreach ($ppcs as $ppc) { ?>
        <tr>
            <td><?php echo $i; ?></td>
            <td><?php echo $ppc->jenis; ?></td>
            <td><?php echo $ppc->keperluan; ?></td>
            <td><?php echo $ppc->status; ?></td>
            <td><?php echo $this->tag->linkTo("/admin/detailreservasipc/".$ppc->id_ppc, "Lihat detail"); ?></td>
        </tr>
    <?php $i++; } ?>
    </tbody>
</table>

<?php    
}
}
else {
echo "You must login to see this page";
header("refresh:2;url=/pengguna/loginpage");
}