<h2>Login using this form</h2>

<?php echo $this->tag->form("pengguna/login"); ?>

    <p>
        <label for="nrp">NRP</label>
        <?php echo $this->tag->textField("nrp"); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>

    <p>
        <?php 
        echo $this->tag->submitButton("Login") . " ";
        echo $this->tag->linkTo("/", "Go back home");
        ?>
    </p>

</form>